### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/elm-architecture-assignment-dcswitzer#1]
Just to be complete, we discussed this in class.

In Elm, you almost never store actual `Html` in your model. You would rather return the message and use the view function to display the corresponding `Html`

**Comment by dcswitzer** [comment]
That is true. At that time i didn't wrote along, so if i have to change it now i have to take some time to think about how to do and implement it. For now i won't change it and focus to finish other assignments. When there is some space i might take a look at it. 
Your explanation then was clarifying.
